// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chghngeolthjinalfajg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZ2huZ2VvbHRoamluYWxmYWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDQ3MzcsImV4cCI6MjA2NTY4MDczN30.rimZr2BBwtcdbHG3_YyGR4SCE7hJaKF5abMf3U9RgsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);